[versions]
kotlin = "2.1.20"
netty = "4.1.131.Final"
protobuf = "4.29.3"
protobuf-plugin = "0.9.6"
grpc = "1.62.2"
grpc-kotlin = "1.4.1"
postgresql = "42.7.10"
hikari = "6.2.1"
lettuce = "6.5.2.RELEASE"
bcrypt = "0.10.2"
java-jwt = "4.5.0"
coroutines = "1.10.1"
typesafe-config = "1.4.3"
flyway = "11.1.0"
slf4j = "2.0.16"
logback = "1.5.16"
koin = "4.0.2"

[libraries]
netty-all = { module = "io.netty:netty-all", version.ref = "netty" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
grpc-netty = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
lettuce = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafe-config" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
